### ISSUE TITLE
error

### ISSUE THREAD

**Issue by luyang14** [AndrewTabs1038/Wiegand-Analyzer#1]
![无标题](https://github.com/user-attachments/assets/2dca828f-526a-44bb-a8fd-4c910de2db7d)
Can you help me, please
I installed vs2019 but I don't know how to compile source code

**Comment by AndrewTabs1038** [comment]
Hello, please send the .sal file that you are working with.

**Comment by ruahriman** [comment]
I have the same error at other data pattern. 
42 data bits, plugin configuration is default.
Error after first frame.
![sc](https://github.com/user-attachments/assets/f50f7a82-2b8a-4e5c-8ce2-3f13ba664419)

[Session 0.zip](https://github.com/user-attachments/files/16894989/Session.0.zip)
2nd issue: plugin is path-dependent. As we see on screenshot from [luyang14](https://github.com/luyang14),  plugin is searching vector library at default istallation path. 
In example, i have not much space on drive C and wanna install VS2022 (with unknown component list) on D for this plugin, but i can't

**Comment by AndrewTabs1038** [comment]
@ruahriman Thank you for letting me know and supplying a .sal file! It helps me improve the program. It seems like that with utilizing vectors may cause problems with larger samples that I didn't experience when testing the program. I will be removing the use of vectors all together once I have time, which I believe would fix your second issue as well.

**Comment by AndrewTabs1038** [comment]
@ruahriman I have fixed the issues, there is no longer a use of vectors. Again, thank you for you help in identifying this issue.

![image](https://github.com/user-attachments/assets/9709e885-abe6-44d1-9781-5d38330c4fb6)
